version: '3'

services:

#  gamrabbitmqgam:
#    container_name: gamrabbitmqgam
#    hostname: "gamrabbitmq"
#    image: "rabbitmq"
#    extends:
#      file: ./rabbitmq/rabbitmq.yml
#      service: rabbitmqgam
#    environment:
#      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
#      RABBITMQ_DEFAULT_USER: "rabbitmq"
#      RABBITMQ_DEFAULT_PASS: "rabbitmq"
#      RABBITMQ_HOST: "rabbitmqplatform"
#      RABBITMQ_PORT: "5672"
#      RABBITMQ_DEFAULT_VHOST: "/"
#    ports:
#      - "15672:15672"
#      - "5672:5672"
#    labels:
#      NAME: "rabbitmqgam"

  gambackoffice:
    container_name: gambackoffice
    image: node:14
    working_dir: /backoffice
    build:
      context: ./../backoffice
    command: "npm start"
    environment:
      - NODE_ENV=development
      - NODE_PORT=3000
    volumes:
      - ./../backoffice:/backoffice
#    links:
#      - gaminatormysql
    expose:
      - 3000
    ports:
      - 3000:3000
