version: '2'

services:

  rabbitmqgam:
    container_name: rabbitmqgam
    hostname: "rabbitmqgam"
    image: "rabbitmq"
    extends:
      file: ./rabbitmq/rabbitmq.yml
      service: rabbitmqgam
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_HOST: "rabbitmqplatform"
      RABBITMQ_PORT: "5672"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmqgam"
